"""Data models for Composer Engine."""

from composer_engine.models.automation import AutomationCurve, AutomationPoint, Marker
from composer_engine.models.analysis import (
    AnalysisResult,
    CounterpointReport,
    DynamicProfile,
    MoodProfile,
    Motif,
    Phrase,
    RhythmProfile,
    StructureSegment,
    StyleMatch,
    VoiceLeadingIssue,
)
from composer_engine.models.chord import CadenceType, Chord, ChordQuality
from composer_engine.models.enums import (
    AUTOMATION_CC,
    DEFAULT_GM_PROGRAMS,
    DRUMS_CHANNEL,
    GM_PERCUSSION,
    AutomationParam,
    BassMode,
    BrassMode,
    DrumStyle,
    GrooveName,
    GuitarMode,
    HiHatPattern,
    HumanizeType,
    InstrumentType,
    KickPattern,
    Key,
    Mode,
    PianoMode,
    SectionType,
    SnarePattern,
    Stage,
    StringsMode,
    StylePreset,
    SynthMode,
    WoodwindsMode,
)
from composer_engine.models.global_settings import GlobalSettings
from composer_engine.models.note import Note
from composer_engine.models.section import Section
from composer_engine.models.song import Song
from composer_engine.models.track import Track

__all__ = [
    "AutomationParam",
    "AUTOMATION_CC",
    "DEFAULT_GM_PROGRAMS",
    "DRUMS_CHANNEL",
    "GM_PERCUSSION",
    "AutomationPoint",
    "AutomationCurve",
    "Marker",
    "AnalysisResult",
    "Phrase",
    "Motif",
    "RhythmProfile",
    "VoiceLeadingIssue",
    "CounterpointReport",
    "StyleMatch",
    "MoodProfile",
    "DynamicProfile",
    "StructureSegment",
    "Key",
    "Mode",
    "SectionType",
    "InstrumentType",
    "Stage",
    "BassMode",
    "DrumStyle",
    "HiHatPattern",
    "KickPattern",
    "SnarePattern",
    "StringsMode",
    "BrassMode",
    "WoodwindsMode",
    "SynthMode",
    "PianoMode",
    "GuitarMode",
    "HumanizeType",
    "GrooveName",
    "StylePreset",
    "ChordQuality",
    "CadenceType",
    "Chord",
    "Note",
    "Track",
    "Section",
    "GlobalSettings",
    "Song",
]
